version: '3.8'  # Specify the version of Docker Compose

services:
  postgres:
    image: postgres:13.11-bullseye
    container_name: java-spring-boot-boilerplate-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0.12-alpine
    container_name: java-spring-boot-boilerplate-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass "secret"
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:redis-commander-210
    restart: always
    container_name: java-spring-boot-boilerplate-redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: secret
      HTTP_USER: admin
      HTTP_PASSWORD: secret
    ports:
      - '6380:8081'

volumes:
  postgres-data: {}
  redis-data: {}