apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: springboot-api
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: springboot-api
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50